name: Angular GitHub CI/CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          npm ci
      - name: Lint
        run: |
          npm run lint
      - name: Test
        run: |
          npm run test -- --prod
      - name: Build
        run: |
          npm run build -- --prod
      - name: Deploy to GH Pages
        if: github.ref == 'refs/heads/main'
        run: |
          cd docs
          echo axiepad.com >> CNAME
          git init
          git config user.name  "CI"
          git config user.email "user@example.com"
          git status
          git remote add origin https://${{secrets.ACCESS_TOKEN}}@github.com/Jsuppers/axie-pad.git
          git checkout -b gh-pages
          git add --all
          git commit -m "update"
          git push origin gh-pages -f
